[project]
name = "youtube-automanager"
version = "0.1.2"
description = "Adds videos to your YouTube playlists automatically based on rules"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "fastapi",
    "global-logger",
    "google-api-python-client",
    "google-auth-oauthlib",
    "knockknock",
    "oauth2client",
    "pendulum",
    "python-worker",
    "python-youtube",
    "pyyaml",
    "sqlalchemy",
    "trustme",
    "uvicorn",
]

[dependency-groups]
dev = [
    "pre-commit-uv",
    "ruff",
]
